### ISSUE TITLE
Store EAS onto IPFS

### ISSUE THREAD

**Issue by metalboyrick** [fractaldotbox/geist-dapp-kit#12]
variants

- eas sdk
- viem

official example L225
https://github.com/ethereum-attestation-service/met-irl/blob/offchain/src/utils/utils.ts#L225

![Image](https://github.com/user-attachments/assets/050e6d4b-9024-461b-bf84-8d48fdcc5e8b)

**Comment by debuggingfuture** [comment]
@metalboyrick FYR I'm working on lighthouse sdk (ipfs/filecoin)

https://github.com/fractaldotbox/geist-dapp-kit/pull/13

**Comment by metalboyrick** [comment]
@debuggingfuture shall i wait until your pr is merged to start?

**Comment by debuggingfuture** [comment]
blocked by [DAPPK-30](https://huly.app/browse/?workspace=w-githubdebugg-geist-6740368e-54581cea9a-bcad80&_class=tracker%3Aclass%3AIssue&_id=6742f5e33984595f584ffe61&label=DAPPK-30)
