### ISSUE TITLE
[DappKit] Wallet - Privy Hello World story

### ISSUE THREAD

**Issue by debuggingfuture** [fractaldotbox/geist-dapp-kit#14]
- react only

In this story, I am able to create/open my privy wallet\
it should look more or less https://demo.privy.io/

If you need more settings for privy, you can create your own testing account to try

### test account

privy app
geist-dappkit-test

under `geist@debuggingfuture.com`

app ID
`cm2vi1gua0aukbq4p69w3rphl`

app secret
`656nfrEEov64tHvaLQSUE5MMNe65CzH6z1PJRFUYSJjaWf8tyvJE4gjS4GaYR89EUAJCdvErKw7vYG6ZSpwdLkAj`

**Comment by iyansr** [comment]
<https://github.com/fractaldotbox/geist-dapp-kit/pull/38>
