### ISSUE TITLE
Transfer button (Wagmi)

### ISSUE THREAD

**Issue by debuggingfuture** [fractaldotbox/geist-dapp-kit#15]
In this story, create an input and button that will transfer the specified amount from connected account to selected receipent (account)

(must hv)

- use shadcn default styles
- use wagmi
- able to specify recipeint. use vitalike (`0xd8da6bf26964af9d7eed9e03e53415d37aa96045`) as default in story

(nice to hv)

- support ENS, use exist util to resolve address

mock up
![Image](https://github.com/user-attachments/assets/0dec6034-41b2-4ff3-b25a-a505494a4f5e)

---

In future, we want to integrate wallet and cover more scenarios like this
https://onchainkit.xyz/transaction/transaction

**Comment by iyansr** [comment]
https://github.com/fractaldotbox/geist-dapp-kit/pull/22

**Comment by debuggingfuture** [comment]
Estimations:
- Expected
- Actual: 1.5 hr

**Comment by debuggingfuture** [comment]
Monthly $ salary
- Part-time hour based rate
- Distribution ratio
  Gitcoin 10k 

Iyan x% - (calculated by hours conribution) 
airdrop
salary by hour + airdrop by contributions
