### ISSUE TITLE
[DappKit] Transaction table

### ISSUE THREAD

**Issue by metalboyrick** [fractaldotbox/geist-dapp-kit#28]
refers https://eth.blockscout.com/txs

<sub><a href="https://huly.app/guest/geist?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQyZWRhOGQyZWY0Y2JjYzQ2ODVkZDYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZGVidWdnLWdlaXN0LTY3NDAzNjhlLTU0NTgxY2VhOWEtYmNhZDgwIn0.mLo-La6ObaLD6axBHFSdfhHSjiqE-JP1VQvDLeZPTEc">Huly&reg;: <b>DAPPK-28</b></a></sub>

**Comment by metalboyrick** [comment]
@debuggingfuture @justin-lau taking up this one if you guys are ok

**Comment by justin-lau** [comment]
> @debuggingfuture @justin-lau taking up this one if you guys are ok

I recall @debuggingfuture mentioning in the meeting that he was working on this by reusing the lower level components. Please wait for his clarification to ensure there won't be any overlaps.

**Comment by metalboyrick** [comment]
[debuggingfuture (Vincent](https://huly.app/browse/?workspace=w-githubdebugg-geist-6740368e-54581cea9a-bcad80&_class=contact%3Aclass%3APerson&_id=6740369e28e438f612247d3e&label=debuggingfuture%20(Vincent) Opened a PR, see if this is the entries we want. <https://github.com/fractaldotbox/geist-dapp-kit/pull/37>
